export const Keys = {
  Queries: {
    VALIDATE_SESSION: "VALIDATE_SESSION",
    DASHBOARD_STATS: "DASHBOARD_STATS",
    GET_VIOLENCES: "GET_VIOLENCES",
    GET_VIOLENCE_OPTIONS: "GET_VIOLENCE_OPTIONS",
    GET_VIOLENCE_TYPES: "GET_VIOLENCE_TYPES",
    GET_VIOLENCE_FLAGS: "GET_VIOLENCE_FLAGS",
    GET_SERVICES: "GET_SERVICES",
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_ROLES: "GET_ROLES",
    GET_USERS: "GET_USERS",
    GET_VICTIMS: "GET_VICTIMS",
    GET_ORGANIZATIONS: "GET_ORGANIZATIONS",
  },
  Mutations: {
    SIGNIN: "SIGNIN",
    ADD_VIOLENCE: "ADD_VIOLENCE",
    ADD_SERVICE: "ADD_SERVICE",
    ADD_COUNTRY: "ADD_COUNTRY",
    ADD_ROLE: "ADD_ROLE",
    ADD_USER: "ADD_USER",
    ADD_ORGANIZATION: "ADD_ORGANIZATION"
  },
};
