export const Keys = {
  Queries: {
    VALIDATE_SESSION: "VALIDATE_SESSION",
    DASHBOARD_STATS: "DASHBOARD_STATS",
    GET_VIOLENCES: "GET_VIOLENCES",
  },
  Mutations: {
    SIGNIN: "SIGNIN",
    ADD_VIOLENCE: "ADD_VIOLENCE"
  },
};
