export const Keys = {
  Queries: {
    VALIDATE_SESSION: "VALIDATE_SESSION",
    DASHBOARD_STATS: "DASHBOARD_STATS",
    GET_VIOLENCES: "GET_VIOLENCES",
    GET_SERVICES: "GET_SERVICES"
  },
  Mutations: {
    SIGNIN: "SIGNIN",
    ADD_VIOLENCE: "ADD_VIOLENCE",
    ADD_SERVICE: "ADD_SERVICE"
  },
};
